# Generated by Django 5.0.6 on 2024-05-29 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='writer',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
