#Github CI/CD
---
name : Checks #Workflow 이름

on : [push]

jobs :
  test-link :
    name : Test and Lint
    runs-on : ubuntu-20.04 #작업 환경
    steps : #작업 단계
      - name : Login in to Docker Hub
        uses : docker/login-action@v1
        with : 
          username : ${{ secrets.DOCKERHUB_USER }}
          password : ${{ secrets.DOCKERHUB_PASSWORD }}
      - name : Check out #Github 코드를 가져오는 역할
        uses : actions/checkout@v2
      - name : Run TestCode
        run : docker-compose run --rm app sh -c 'python manage.py test'
      - name : Run Flake8 for Lint Check #pep8 스타일 가이드를 잘 준수하고 있는지 체크
        run : docker-compose run --rm app sh -c 'flake8'